from matplotlib import pyplot as plt


def draw_lines(epochs, mean_recalls, mean_precisions, mean_accuracies, mean_F1s):
    plt.subplot(221)
    plt.xticks([i+1 for i in range(epochs)])
    plt.xlabel('epoch')
    plt.ylabel('Recall %')
    plt.title('Recall')
    plt.plot([i + 1 for i in range(epochs)], mean_recalls)
    plt.subplot(222)
    plt.xticks([i + 1 for i in range(epochs)])
    plt.xlabel('epoch')
    plt.ylabel('Precision %')
    plt.title('Precision')
    plt.plot([i + 1 for i in range(epochs)], mean_precisions)
    plt.subplot(223)
    plt.xlabel('epoch')
    plt.ylabel('Accuracy %')
    plt.xticks([i + 1 for i in range(epochs)])
    plt.title('Accuracy')
    plt.plot([i + 1 for i in range(epochs)], mean_accuracies)
    plt.subplot(224)
    plt.xlabel('epoch')
    plt.ylabel('F1 score %')
    plt.xticks([i + 1 for i in range(epochs)])
    plt.title('F1 score')
    plt.plot([i + 1 for i in range(epochs)], mean_F1s)
    plt.savefig('metrics.png', bbox_inches='tight')
